name: Publish ARM Image
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build & Publish
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "Build & Publish to registry"
          pkg_version=$(cat package.json | jq -r '.version')
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t house_searching_notifier ./
          docker tag house_searching_notifier ${{ secrets.DOCKERHUB_USERNAME }}/house_searching_notifier:$pkg_version
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/house_searching_notifier:$pkg_version
