name: Publish ARM Image
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build & Publish
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/house_searching_notifier:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/house_searching_notifier:buildcache,mode=max
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/house_searching_notifier:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
