name: Publish ARM Image
on:
  push:
    branches:
      - 'main'
jobs:
  printInputs:
    runs-on: self-hosted
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.name }}"
  build:
    name: Build & Publish
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/house_searching_notifier:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
